### ISSUE TITLE
NullPointerException if a row is empty

### ISSUE THREAD

**Issue by afermi** [chenjianjx/ssio#5]
Hi, 

trying to use your library to parse a xlsx file, we discover a bug in the class OfficeRow.java at row 35.

Indeed, if a row in the Excel sheet is empty, the instance poiRow is null. 
Then invoking its method getLastCellNum() at row 35 throws a NullPointerException.

![image](https://user-images.githubusercontent.com/22451146/144472861-651f0c93-d906-4c54-83e5-72b6f35261c2.png)

To overcome the issue we tried the following: in the class OfficeSheet.java at row 40  we control if the instance poiRow is null. If it is the case, we simply step further in the loop (from some tests it seems to work correctly).

![image](https://user-images.githubusercontent.com/22451146/144472940-d304d0ee-0131-49e8-a16a-25615cc5a6b8.png)

Is it a good solution or could be solved in a better way?

**Comment by chenjianjx** [comment]
Hi @afermi ,  thank you for the report. 
Yes, I'll take a look sometime.   

If possible can you upload an *.xlsx file that may cause this problem (masking your sensitive data, of course)?

**Comment by chenjianjx** [comment]
Hi @afermi ,  it's fixed in version 1.0.1 (already in central maven repo) 

If you are interested, you can check out the fix here:  https://github.com/chenjianjx/ssio/pull/6

**Comment by afermi** [comment]
Thank you so much @chenjianjx! 
I am going to check immediately if the version 1.0.1suits our needs.
